name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build:static
